### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [ilona1986/grid_template#21]
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.

![image](https://user-images.githubusercontent.com/8464662/130483066-72f7e4f6-cbae-45d7-975f-57752f2b63b2.png)

**Comment by ilona1986** [comment]
![image(1)](https://user-images.githubusercontent.com/52574833/130487648-023a20fd-8d68-41d0-bb6e-e26c74492f29.png)

В макете белая border bottom , а в мастер шаблоне ее нет . Скрин мастера. Так есть разночтения в макете и в мастер шаблоне ,приняли за оригинал мастер.

![image(2)](https://user-images.githubusercontent.com/52574833/130488886-eadf1deb-59b1-4f6a-9f8e-47f4a286a5c8.png)
А это наша работа. Или может вопрос в другом?

**Comment by Alecto** [comment]
пн, 23 авг. 2021 г. в 20:15, Ilona ***@***.***>:

> [image: image(1)]
> <https://user-images.githubusercontent.com/52574833/130487648-023a20fd-8d68-41d0-bb6e-e26c74492f29.png>
>

[image: image.png]
в макете все также, нет никаких "разночтений", за фотопиа я не отвечаю


>
> <https://user-images.githubusercontent.com/52574833/130487648-023a20fd-8d68-41d0-bb6e-e26c74492f29.png>
>
> В макете белая border bottom , а в мастер шаблоне ее нет . Скрин мастера.
> Так есть разночтения в макете и в мастер шаблоне ,приняли за оригинал
> мастер.
>
> [image: image(2)]
> <https://user-images.githubusercontent.com/52574833/130488886-eadf1deb-59b1-4f6a-9f8e-47f4a286a5c8.png>
> А это наша работа. Или может вопрос в другом?
>
в другом вопрос, ищите отличия дальше, только обсуждали в телеге

**Comment by VadimVit** [comment]
Добрый день, внесли изменения в placeholder 
![2021-08-26_12-53-13](https://user-images.githubusercontent.com/85961686/130942751-f007f316-307b-485d-b37d-5d2e8ee44ea5.png)

**Comment by Alecto** [comment]
как посмотреть?
2 ссылочки пожалуйста

чт, 26 авг. 2021 г. в 12:57, Вадим ***@***.***>:
